name: Build-Test-Coverage

on:
  push:
    branches: [ main, develop, feature* ]
  pull_request:
    branches: [ main, develop, feature* ]
    
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    environment: pipelines
    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    steps:
    - uses: actions/checkout@v3
    
    - name: echo
      env:
          LATEST_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || format('latest-{0}', github.ref_name) }}
      run: |
        echo "LATEST_TAG is ${{env.LATEST_TAG}}"    
        echo "github.ref is ${{ github.ref }}"
        echo "github.ref_name is ${{ github.ref_name }}"
        echo "github.event.pull_request.merged is ${{ github.event.pull_request.merged }}"
        echo "github.event_name is ${{ github.event_name }}"
    
    - name: test
      env:
          LATEST_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || format('latest-{0}', github.ref_name) }}
      if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref_name == 'refs/heads/develop' || startsWith(github.ref_name, 'hotfix') || startsWith(github.ref_name, 'release')) }}
      run: |
        echo "today is ${{env.LATEST_TAG}}"
