name: Build-Test-Coverage

on:
  push:
    branches: [ main, develop, feature* ]
  pull_request:
    branches: [ main, develop, feature* ]
    
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    environment: pipelines
    strategy:
      matrix:
        dotnet-version: ['7.0.x']

    steps:
    - uses: actions/checkout@v3
    - name: test
      env:
          LATEST_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || format('latest-{0}', github.ref_name) }}
      if: ${{ success() && (github.ref == 'refs/heads/main' || github.ref_name == 'refs/heads/develop' || startsWith(github.ref_name, 'hotfix') || startsWith(github.ref_name, 'release')) }}
      run: |
        echo "today is ${{env.LATEST_TAG}}"
